apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ghost.hekv.org
spec:
  secretName: ghost.hekv.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - ghost.hekv.org
